### PR TITLE
fix(Connections): SourceIP filter and tagging

### LINKED ISSUE #1284: mihomo inner dns can't be filrered
It appears as empty in combo and when selected it does nothing.
yacd-meta is okay. It appears as internal connection.

### PR DESCRIPTION
**Pull request by Plutonium141**
Fix #1284

### CODE REVIEW

File: src/components/ConnectionsSettingsModal.tsx [hunk 1]
```diff
@@ -93,8 +91,8 @@ const TagClientSourceIPWithNameForm: Component = () => {
               )}
           >
             {(sourceIP) => (
-              <option class="badge" value={sourceIP()}>
-                {sourceIP()}
+              <option class="badge" value={sourceIP() || 'Inner'}>
```
Comment (kunish) [inline src/components/ConnectionsSettingsModal.tsx:94]: Maybe we should consider adding a translation for this?
